<?php
namespace Patter\Decorator;

class ConcreteDecorator extends Decorator {

    public function __construct(Component $component)
    {
        parent::__construct($component);
    }

    public function operation()
    {
        parent::operation(); // TODO: Change the autogenerated stub
        $this->addFunction();
    }

    public function addFunction() {
        echo "为具体构件角色增加额外的功能addedFunction()";
        echo "</br>";
    }
}